fix: cargo test does not capture tracing logs (#3481)
* fix: cargo test does not capture tracing logs

Use test-log crate that solves this problem

- hotshot tests: initialize_logging -> test_log
- sequencer: setup_test -> test_log

* fix: double test_log wrapping in rstest template

* test_log: wrap tests in api.rs

* sequencer api tests: generic_tests -> rstest

With generic_tests I get:

error: test failed, to rerun pass `-p sequencer --lib`

Caused by: process didn't exit successfully: ...
    11, SIGSEGV: invalid memory reference)