fix: implementation contract used as target (#3861)
* fix: implementation contract used as target

Fixes errors like

      Error: Invalid contract type for timelock
      derivation: ESPRESSO_SEQUENCER_ESP_TOKEN_V2_ADDRESS

If we do the ownership transfer after an upgrade we need to explicitly
use the proxy.

Small refactoring to make some runtime errors impossible and convert
some late errors into erros during clap argument parsing.

* clippy