rust 1.89 -> 1.90 (#3616)
* rust 1.89 -> 1.90

fix clippy

- use `is_multiple_of`
- remove some dead code
- update flake.lock, leave that to
  https://github.com/EspressoSystems/espresso-network/pull/3601

* nix: remove deprecated apple_sdk

* allow unused_attributes in contract bindings

* nix: fix flake.nix on darwin

Fixes:

    error: linking with `cc` failed: exit status: 1
    ...
    = note: Multiple conflicting values defined for DEVELOPER_DIR_arm64_apple_darwin
            Existing value is /nix/store/rhlyld20zdzdi5wghb4b12gw52s9whr9-apple-sdk-11.3
            Attempting to set to /nix/store/ywb67nwhda4n7lww0dyw394hd7gqw1sr-apple-sdk-12.3 via DEVELOPER_DIR_FOR_TARGET

* Revert "allow unused_attributes in contract bindings"

This reverts commit 6b7182dee3aa9f169c8f2bb5543325a8f3fbc74b.

* Reapply "allow unused_attributes in contract bindings"

This reverts commit 9fc47087ccff9e3712498ca74af4d0b25a84bf72.

* link foundry issue