sequencer api tests: generic_tests -> rstest
With generic_tests I get:

error: test failed, to rerun pass `-p sequencer --lib`

Caused by: process didn't exit successfully: ...
    11, SIGSEGV: invalid memory reference)